
version: "3.9"

networks:
  kong-net:
    driver: bridge

services:
  kong:
    image: kong:2.5.0-alpine
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    ports:
      - "8000:8000"   # Proxy HTTP
      - "8443:8443"   # Proxy HTTPS
      - "8001:8001"   # Admin API
      - "8444:8444"   # Admin HTTPS
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    networks:
      - kong-net

  items:
    build:
      context: ./items
    container_name: items
    expose:
      - "8000"
    networks:
      - kong-net

  users:
    build:
      context: ./users
    container_name: users
    expose:
      - "8000"
    networks:
      - kong-net

  shops:
    build:
      context: ./shops
    container_name: shops
    expose:
      - "8000"
    networks:
      - kong-net



# version: '3.7'

# services:
#   kong:
#     image: kong:3.1
#     container_name: kong
#     environment:
#       KONG_DATABASE: postgres
#       KONG_PG_HOST: keycloak-db
#       KONG_PG_PASSWORD: kongpassword
#       KONG_PG_USER: konguser
#       KONG_PROXY_ACCESS_LOG: /dev/stdout
#       KONG_ADMIN_ACCESS_LOG: /dev/stdout
#       KONG_PORT_MAPS: '8000:8000'
#       KONG_PORTS: '8000, 8443'
#       KONG_ADMIN_PORT: '8001'
#       KONG_ADMIN_GUI_HOST: kong.local
#       KONG_ADMIN_GUI_PORT: 8002
#     ports:
#       - "8000:8000"
#       - "8443:8443"
#       - "8001:8001"
#     networks:
#       - dbless_keycloak-network
#     depends_on:
#       - keycloak

#   keycloak-db:
#     image: postgres:latest
#     container_name: keycloak-db
#     environment:
#       POSTGRES_USER: keycloak
#       POSTGRES_PASSWORD: keycloakpassword
#       POSTGRES_DB: keycloak
#     networks:
#       - dbless_keycloak-network
#     volumes:
#       - keycloak-db-data:/var/lib/postgresql/data

#   keycloak:
#     image: quay.io/keycloak/keycloak:latest  # Use this updated image # Updated to use Docker Hub's Keycloak image
#     container_name: keycloak
#     environment:
#       KEYCLOAK_USER: admin
#       KEYCLOAK_PASSWORD: admin
#       DB_VENDOR: POSTGRES
#       DB_ADDR: keycloak-db
#       DB_DATABASE: keycloak
#       DB_USER: postgres
#       DB_PASSWORD: 12345
#     ports:
#       - "8080:8080"
#       - "8443:8443"
#     networks:
#       - dbless_keycloak-network
#     depends_on:
#       - keycloak-db

#   items:
#     build: ./items
#     container_name: items
#     environment:
#       DB_HOST: keycloak-db
#     ports:
#       - "8001:8001"
#     networks:
#       - dbless_keycloak-network

#   shops:
#     build: ./shops
#     container_name: shops
#     environment:
#       DB_HOST: keycloak-db
#     ports:
#       - "8002:8002"
#     networks:
#       - dbless_keycloak-network

#   users:
#     build: ./users
#     container_name: users
#     environment:
#       DB_HOST: keycloak-db
#     ports:
#       - "8003:8003"
#     networks:
#       - dbless_keycloak-network

# networks:
#   dbless_keycloak-network:
#     driver: bridge

# volumes:
#   keycloak-db-data:
#     driver: local

